Верстка страницы компонента
js-tasks-ru/htmlcss-20231027_ksanster pull request #11
Opened 2023-11-14 21:12 UTC by ksanster

1. Я ведь правильно понимаю, что серым цветом залит весь body?
2. Переопределить flexbox-блок page затруднительно (невозможно?). Сделал отдельный блок template-page с display:grid
3. Тяжело определить, что первично: ширина блока template-page или отступы. Возможно вместо paddings надо было выравнивать блок по центру, но тогда не получится такого отступа слева по умолчанию, он будет зависеть от ширины вьюпорта 
4. Попробовал набросать меню отдельными строчками, хотя сделать его списком наверное было бы более семантично

2023-11-14 21:12 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-11-15 20:59 UTC, GSemikozov commented
> 1. Я ведь правильно понимаю, что серым цветом залит весь body?
> 2. Переопределить flexbox-блок page затруднительно (невозможно?). Сделал отдельный блок template-page с display:grid
> 3. Тяжело определить, что первично: ширина блока template-page или отступы. Возможно вместо paddings надо было выравнивать блок по центру, но тогда не получится такого отступа слева по умолчанию, он будет зависеть от ширины вьюпорта
> 4. Попробовал набросать меню отдельными строчками, хотя сделать его списком наверное было бы более семантично

1) да, как вариант
2) можно через модификатор. Но можно и отдельный блок 
3) если это page, значит ширина должна = ширине вьюпорта, остальное - уже через контейнер
4) достаточно комбинации `nav + a`

2023-11-15 21:00 UTC, GSemikozov requested changes

2023-11-15 21:00 UTC, GSemikozov commented on components/footer/footer.css
>      margin: 0 auto;
лишнее

2023-11-15 21:00 UTC, GSemikozov commented on components/header/header.css
> +    height: 34px;
лишнее

2023-11-15 21:00 UTC, GSemikozov commented on components/template-page/template-page.css
> +    max-width: 1440px;
лишнее

2023-11-15 21:00 UTC, GSemikozov commented on components/template-page/template-page.css
> +    margin: 0 165px 0 165px;
лишнее

2023-11-15 21:00 UTC, GSemikozov commented on components/template-page/template-page.css
> +    max-width: 1110px;
лишнее - у нас ведь чтобы выравнивать контент есть container

2023-11-17 15:42 UTC, ksanster commented on components/template-page/template-page.css
> +    max-width: 1110px;
То есть как и на главной,  мы добавляем внутрь каждого блока в page контейнер для выравнивания контента? Попробовал так сделать, вроде выглядит логично.
Но пришлось добавить к контейнеру в футере модификатор, который делает` text-align: center`, иначе текст в нем никак не хотел выравниваться (

2023-11-17 15:42 UTC, ksanster commented on components/template-page/template-page.css
> +    margin: 0 165px 0 165px;
Убрал

2023-11-17 15:42 UTC, ksanster commented on components/template-page/template-page.css
> +    max-width: 1440px;
Убрал

2023-11-17 15:43 UTC, ksanster commented on components/header/header.css
> +    height: 34px;
Убрал

2023-11-17 15:43 UTC, ksanster commented on components/footer/footer.css
>      margin: 0 auto;
Убрал

2023-11-18 20:42 UTC, GSemikozov approved these changes

2023-11-18 20:42 UTC, merged