Модалка
js-tasks-ru/htmlcss-20231027_ksanster pull request #13
Opened 2023-11-15 14:25 UTC by ksanster

2023-11-15 14:26 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-11-15 14:27 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-11-15 20:55 UTC, GSemikozov requested changes

2023-11-15 20:55 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +.modal__background {
лишний элемент, все это надо добавить на уровень класса блока

2023-11-15 20:55 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +    opacity: 0.5;
лишнее

2023-11-15 20:55 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +    background: #C4C4C4;
это через rgba

2023-11-15 20:55 UTC, GSemikozov commented on 05-lection3/02-modal/modal.css
> +.modal__popup_size {
какой именно size?) например medium?

2023-11-16 16:09 UTC, ksanster commented on 05-lection3/02-modal/modal.css
> +.modal__background {
Сделал

2023-11-16 16:09 UTC, ksanster commented on 05-lection3/02-modal/modal.css
> +    opacity: 0.5;
Перенес в rgba

2023-11-16 16:09 UTC, ksanster commented on 05-lection3/02-modal/modal.css
> +    background: #C4C4C4;
Done

2023-11-16 16:09 UTC, ksanster commented on 05-lection3/02-modal/modal.css
> +.modal__popup_size {
По умолчанию!)
Переименовал

2023-11-18 20:52 UTC, GSemikozov approved these changes

2023-11-18 20:52 UTC, merged