Add solution for 06-lection4/01-avatar
js-tasks-ru/htmlcss-20231027_ksanster pull request #16
Opened 2023-11-24 10:33 UTC by ksanster

В блоке .avatar размеры не задаю, это буду делать либо во враппере, либо модификатором.
Но сам блок должен быть - как было сказано на лекции компонент может быть более комплексным, чем в примере.
Поэтому оставил класс `.avatar` пустым

2023-11-24 10:33 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-11-24 16:04 UTC, GSemikozov requested changes

2023-11-24 16:04 UTC, GSemikozov commented on 06-lection4/01-avatar/avatar.css
> +.avatar {
тут должны быть фиксированные значение для ширины и высоты

2023-11-24 16:28 UTC, ksanster commented on 06-lection4/01-avatar/avatar.css
> +.avatar {
Поправил

2023-11-25 20:47 UTC, GSemikozov approved these changes

2023-11-25 20:47 UTC, merged