Add solution for 07-lection5/02-radiobutton
js-tasks-ru/htmlcss-20231027_ksanster pull request #20
Opened 2023-11-27 18:28 UTC by ksanster

2023-11-27 18:29 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-12-02 19:53 UTC, GSemikozov requested changes

2023-12-02 19:53 UTC, GSemikozov commented on 07-lection5/02-radio/index.html
> +                    <svg class="radio__icon" width="18" height="18" viewBox="0 0 18 18" fill="none" xmlns="http://www.w3.org/2000/svg">
кружок можно и через css отрисовать)

2023-12-04 16:49 UTC, ksanster commented on 07-lection5/02-radio/index.html
> +                    <svg class="radio__icon" width="18" height="18" viewBox="0 0 18 18" fill="none" xmlns="http://www.w3.org/2000/svg">
Да, сделал

2023-12-05 20:56 UTC, GSemikozov approved these changes

2023-12-05 20:57 UTC, merged