Add solution for 07-lection5/04-input
js-tasks-ru/htmlcss-20231027_ksanster pull request #22
Opened 2023-11-28 14:56 UTC by ksanster

2023-11-28 14:56 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-12-02 19:55 UTC, GSemikozov requested changes

2023-12-02 19:55 UTC, GSemikozov commented on 07-lection5/04-input/index.html
> +            <label class="form-field">
а вот в случае с данным блоком заворачивать в лейбл не надо

2023-12-02 19:55 UTC, GSemikozov commented on 07-lection5/04-input/index.html
> +                Label
именно это и есть лейбл

2023-12-02 19:55 UTC, GSemikozov commented on 07-lection5/04-input/index.html
> +                    <svg class="form-field__icon form-field__icon-valid">
form-field__icon_valid

2023-12-02 19:55 UTC, GSemikozov commented on 07-lection5/04-input/index.html
> +                    <svg class="form-field__icon form-field__icon-invalid">
form-field__icon_invalid

2023-12-02 19:55 UTC, GSemikozov commented on 07-lection5/04-input/index.html
> +                        <use href="#success"></use>
иконки нужно добавить в спрайт

2023-12-02 19:55 UTC, GSemikozov commented on 07-lection5/04-input/input.css
> +    width: 259px;
ограничивать ширину не стоит

2023-12-04 17:39 UTC, ksanster commented on 07-lection5/04-input/index.html
> +                Label
Наверное, если считать это подписью, то более семантично будет проставить всем input'ам id и обернуть подписи в `<label for>`. Чтобы по клику на Label фокус переходил на поле ввода.
Но это скорее уже для конкретного применения, думаю что здесь лишнее

2023-12-04 17:40 UTC, ksanster commented on 07-lection5/04-input/index.html
> +                    <svg class="form-field__icon form-field__icon-valid">
Модификатор, да

2023-12-04 17:40 UTC, ksanster commented on 07-lection5/04-input/index.html
> +                    <svg class="form-field__icon form-field__icon-invalid">
Поправил

2023-12-04 17:40 UTC, ksanster commented on 07-lection5/04-input/input.css
> +    width: 259px;
Убрал

2023-12-04 17:42 UTC, ksanster commented on 07-lection5/04-input/index.html
> +                        <use href="#success"></use>
Добавил в спрайт, бонусом стала невозможность просматривать страницу локально (браузер ограничивает загрузку из file , иконки видны только при запуске под локальным сервером)

2023-12-05 20:57 UTC, GSemikozov commented on 07-lection5/04-input/index.html
> +                Label
на самом деле все верно, так и надо было сделать

2023-12-05 20:57 UTC, GSemikozov commented on 07-lection5/04-input/index.html
> +                    <svg class="form-field__icon form-field__icon-valid">
просто неправильно был записан

2023-12-05 20:58 UTC, GSemikozov commented on 07-lection5/04-input/index.html
> +                        <use href="#success"></use>
да, это ок

2023-12-05 20:58 UTC, GSemikozov requested changes

2023-12-05 20:58 UTC, GSemikozov commented on 07-lection5/04-input/index.html
> +                Label
так что лучше добавить сразу)

2023-12-06 08:57 UTC, ksanster commented on 07-lection5/04-input/index.html
> +                    <svg class="form-field__icon form-field__icon-valid">
Поправил

2023-12-06 09:01 UTC, ksanster commented on 07-lection5/04-input/index.html
> +                Label
Сделал

2023-12-06 21:58 UTC, GSemikozov requested changes

2023-12-06 21:58 UTC, GSemikozov commented on 07-lection5/04-input/index.html
> +                <label for="label">Label</label>
это элемент который надо стилизовать - .form-field__label

2023-12-07 09:23 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-12-07 09:23 UTC, ksanster commented on 07-lection5/04-input/index.html
> +                <label for="label">Label</label>
Сделал

2023-12-07 09:24 UTC, ksanster commented on 07-lection5/04-input/index.html
> +            <label class="form-field">
ок

2023-12-09 20:59 UTC, GSemikozov approved these changes

2023-12-09 20:59 UTC, merged