Табуляция на css
js-tasks-ru/htmlcss-20231027_ksanster pull request #23
Opened 2023-11-30 10:36 UTC by ksanster

Теоретически табуляция работает. Но
1. Не смог сделать серый фон для content-части растянутым на всю ширину страницы. И табы и контент уже внутри одного контейнера и не получилось их разделить по разным
2. Напрягают громоздкие конструкции для описания модификаций для псевдоклассов `:checked` `:hover` и тп. Есть подозрение, что это можно сделать как-то проще

2023-11-30 10:36 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-12-02 19:57 UTC, GSemikozov commented
> Теоретически табуляция работает. Но
> 
> 1. Не смог сделать серый фон для content-части растянутым на всю ширину страницы. И табы и контент уже внутри одного контейнера и не получилось их разделить по разным
> 2. Напрягают громоздкие конструкции для описания модификаций для псевдоклассов `:checked` `:hover` и тп. Есть подозрение, что это можно сделать как-то проще

1. нужно следовать совету из задачи - табы лежат на уровне хедера и футера = блок растягивается на всю ширину. Контейнер следует использовать уже на уровне глубже - где меню и где контент
2. можно, но только через scss)

2023-12-02 19:58 UTC, GSemikozov requested changes

2023-12-02 19:58 UTC, GSemikozov commented on components/tabs/tabs.css
> +.tabs__menu-item-all:checked ~ .tabs__content {
.tabs__menu-item_all + ниже по аналогии исправить модификаторы

2023-12-05 08:09 UTC, ksanster commented on components/tabs/tabs.css
> +.tabs__menu-item-all:checked ~ .tabs__content {
Исправил

2023-12-05 08:10 UTC, ksanster commented on components/tabs/tabs.css
> +.tabs__menu-item-all:checked ~ .tabs__content {
Также поправил верстку - теперь совпадает с макетом

2023-12-05 21:02 UTC, GSemikozov requested changes

2023-12-05 21:02 UTC, GSemikozov commented on components/tabs/tabs.css
> +    flex-grow: 1;
тогда это лишнее (либо лишнее 100%, но grow надо задавать на уровне класса элемента родителя применяя микс6 поскольку только родитель знает будет он флексом или нет)

2023-12-05 21:02 UTC, GSemikozov commented on components/tabs/tabs.css
> +    font-family: Inter;
стили для текста - лучше сразу на соответствующем элементе меню

2023-12-05 21:02 UTC, GSemikozov commented on components/tabs/tabs.css
> +.tabs__menu-item_all:checked ~ .container .tabs__scroller
к чужим компонентам в цепочке селекторов нельзя привязываться, структуру может поменяться и верстка развалится (я про .container).

И в принципе чтобы ниже избежать дублирований нужно описать общую логику - `.tabs__menu-item:checked ~ ... .tabs__menu-selector {}` и тд

2023-12-06 22:00 UTC, GSemikozov approved these changes

2023-12-06 22:00 UTC, merged