Верстка макета для "введения в "БЭМ"
js-tasks-ru/htmlcss-20231027_ksanster pull request #5
Opened 2023-11-06 13:23 UTC by ksanster

По поводу задания "позиционирующих" свойств для элементов блоков.
В header'е сделал как было показано на уроке - через вспомогательный container
В footere попробовал реализовать то же самое через модификаторы - мне показалось, что это укладывается в БЭМ-парадигму. Поправьте, если не так

2023-11-06 13:24 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-11-06 16:15 UTC, GSemikozov requested changes

2023-11-06 16:15 UTC, GSemikozov commented on components/preview/preview.css
> +<<<<<<< HEAD
а вот это называется неисправленный конфликт))
нужно оставить что надо, остальное удалить

2023-11-06 16:15 UTC, GSemikozov commented on components/footer/footer.css
> +.footer_inner_content {
а почему применяем модификатор .footer к 2 его разным элементам?)
если хочется ограничить по ширине текст - то это можно сделать на уровне самого элемента, он такой один, модфикатор не нужен

2023-11-06 16:38 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-11-06 16:40 UTC, ksanster commented on components/preview/preview.css
> +<<<<<<< HEAD
Исправил

2023-11-06 16:49 UTC, ksanster commented on components/footer/footer.css
> +.footer_inner_content {
Понятно, что в этом конкретном случае лучше сделать на уровне самого элемента. Я хотел продемонстрировать именно альтернативу заворачивания конкретного элемента в дополнительный контейнер (а заодно, наверное, и недостатки такого подхода).

2023-11-06 16:57 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-11-06 21:03 UTC, GSemikozov commented on components/footer/footer.css
> +.footer_inner_content {
можно использовать и эту альтернативу, только неправильно использовать модификатор блока для модификации его элементов - модификатор используется всегда либо к блоку либо к конкретному элементу, и привязан к нему он в имени класса, например .footer_small - это модификатор блока .footer, а вот .footer__text_small - это уже модификатор элемента блока .footer который называется .footer__text

2023-11-07 05:47 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-11-07 05:53 UTC, jsru commented
Решение было обновлено, посмотрим что скажет @GSemikozov

2023-11-07 05:55 UTC, ksanster commented on components/footer/footer.css
> +.footer_inner_content {
Понял, спасибо.
В этом конкретном случае применил модификатор к боку footer - ведь это его ширину задает модификатор.

2023-11-08 06:52 UTC, GSemikozov commented on components/footer/footer.css
> +.footer_inner_content {
а вот как раз ко всему футеру применять и не надо) футер же должен тянуться на всю ширину страницы и заливать фон белым

2023-11-08 07:44 UTC, ksanster commented on components/footer/footer.css
> +.footer_inner_content {
Сделал как и в header -  обернул содержимое footer в дополнительный контейнер (

2023-11-08 09:27 UTC, GSemikozov reviewed
и - конфликт в МР

2023-11-08 09:27 UTC, GSemikozov commented on index.html
> +                <div class="footer_inner_content">
если это элемент а не модификатор - тогда footer__inner

2023-11-08 10:08 UTC, ksanster commented on index.html
> +                <div class="footer_inner_content">
Так, запутался.
Когда на лекции разбирали верстку этого макета - в хедере вы использовали div-обертку класса container для позиционирования внутренних элементов. При этом говорилось, что это "вынужденное отступление от принципов БЭМ для упрощения конкретной задачи" - по крайней мере я так понял. Эта обертка не была элементом и именовалась не в соответствии с правилами БЭМ, почему в футере должно быть не так?

2023-11-08 20:57 UTC, jsru commented
Добавляю преподавателя (@GSemikozov) для код-ревью.

2023-11-08 20:58 UTC, ksanster commented on index.html
> +                <div class="footer_inner_content">
Да, в этом случае это явно не модификатор. Переименовал

2023-11-09 21:53 UTC, GSemikozov approved these changes

2023-11-09 21:53 UTC, merged